### ISSUE TITLE
Breaking change: `validate_encryption` replaced with `tls_options`

### ISSUE THREAD

**Issue by jch** [github/github-ldap#103]
https://github.com/github/github-ldap/pull/102 made a breaking change to the initializer. Noting this here to add a follow up PR to make it backwards compatible before the next release.

/cc @dbussink @jonabc

**Comment by jonabc** [comment]
@jch, I don't think it's a breaking change.  @dbussink's PR was off my branch for #101, which added in the validate_encryption option.  So net effect from current release is that an option was added, but nothing changed or removed.

**Comment by jonabc** [comment]
Also worth adding that the behavior should be equivalent to the current default when the new initializer option is not given.

**Comment by jch** [comment]
@jonabc thanks I missed the base branch for that pr. Could you add a comment in your PR to recommend the use of the new option instead of the existing one? We can formally deprecate the older option in a follow up.

**Comment by jonabc** [comment]
@jch not sure what you mean.  What is the existing option and which older option would be formally deprecated?  If you mean `validate_encryption`, that option doesn't exist in master.

**Comment by jch** [comment]
Sorry for the confusion. `validate_encryption` as a new proposed option in https://github.com/github/github-ldap/pull/101/commits/c8007663132028f0ce41903f47f208807e52f9a4 that was replaced with `tls_options` during review. Master never had either options.
