### ISSUE TITLE
TCP sockets left open leading to file descriptor exhaustion

### ISSUE THREAD

**Issue by linosgian** [github/github-ldap#105]
Hey!

We are evaluating `github-ldap` as a replacement for the LDAP team syncing, since we will move to SAML auth. We are hosting our own Github Enterprise instance internally.

We've been running this for a couple of weeks and this week we found out that the app was throwing errors (excerpt shown below).
The issue clearly states that we've reached the host's ulimit, and thus we cannot establish new connections. After listing all open TCP connections the result was that a lot of connections were left open on the client side (on CLOSE_WAIT state):

```
Jan 14 08:00:00 teamsync gunicorn3[31171]: github3.exceptions.ConnectionError: <class 'requests.exceptions.ConnectionError'>: A connection-level exception occurred: HTTPSConnectionPool(host='github.skroutz.gr', port=443): Max retries exceeded with url: /api/v3/app/installations?per_page=100 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f664b09b978>: Failed to establish a new connection: [Errno 24] Too many open files'))

$ netstat -ta
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp6      25      0 github-ldap.instance:40248 github-enterprise.instance:https CLOSE_WAIT 
tcp6      25      0 github-ldap.instance:51326 github-enterprise.instance:https CLOSE_WAIT 
tcp6      25      0 github-ldap.instance:58482 github-enterprise.instance:https CLOSE_WAIT 
tcp6      25      0 github-ldap.instance:41444 github-enterprise.instance:https CLOSE_WAIT 
tcp6      25      0 github-ldap.instance:45118 github-enterprise.instance:https CLOSE_WAIT 
tcp6      25      0 github-ldap.instance:34604 github-enterprise.instance:https CLOSE_WAIT 
[...]
```
We've dug into this and here's what we've found up to this point.

Everytime `sync_all_teams` runs, two new [GitHubEnterprise](https://github.com/sigmavirus24/github3.py/blob/404ea04710247407ca9c6bc4f2b89f0e464c4a5e/src/github3/github.py#L67) objects that initialize a GithubSession object are created. `GithubSession` extends the [requests.Session](https://github.com/psf/requests/blob/master/requests/sessions.py#L337) that holds a connection pool across multiple requests (also keeping some state such as cookies etc)

Adding attributes to `_app_ctx_stack` does not seem to survive across
requests, therefore on every single run, new GithubEnterprise objects are created.
Also, some reference to `_app_ctx_stack.top.githubapp_installation` is held somewhere, hence
these GitHubEnterprise objects are never garbage collected, alongside
their connection pools that reside in the underlying GithubSession object.

This leads to leaking requests.Session objects effectively. Eventually,
after several runs of `sync_all_teams` we end up reaching the host's
ulimit, and thus, no new connections can be opened after this point.

We've worked around this issue by popping the `_app_ctx_stack.top` from the
stack. This lets the GitHubEnterprise objects get garbage collected and
so close the open connections on our side (hanging on `CLOSE_WAIT`
state).

```
diff --git a/app.py b/app.py
index ac33caf..d435172 100644
--- a/app.py
+++ b/app.py
@@ -6,7 +6,7 @@ import logging
 
 from apscheduler.schedulers.background import BackgroundScheduler
 from apscheduler.triggers.cron import CronTrigger
-from flask import Flask
+from flask import Flask, _app_ctx_stack
 
 from githubapp import GitHubApp, LDAPClient, CRON_INTERVAL, TEST_MODE
 
@@ -258,6 +258,7 @@ def sync_all_teams():
                     slug=team.slug,
                     config_dir=config_dir
                 )
+    _app_ctx_stack.pop()
 
 
 if __name__ == '__main__':
```
If I understand correctly, `_app_ctx_stack` shouldn't be used that way, but rather use it to share state between functions for a single request and not to hold some global state. Some other in-memory store could be used for this I suppose.

I am not sure what the _correct_ fix would be, but the more frequent the syncing is (CRON_INTERVAL), the sooner people will run into this.

**Comment by mtodd** [comment]
@linosgian I believe you are looking for a different library. Closing as this is unrelated to this repository.
