### ISSUE TITLE
Github robots giving false positives

### ISSUE THREAD

**Issue by hhsadiq** [github/github-ldap#97]
I am an active github user working with two organisations. I push code almost on daily basis and participate in issues discussion for various libraries. Recently github robots blocked my profile from public when I reported an issue for EduSec repo. I reported this problem at support and profile was restored in less than half an hour. I was actively working from my office and this blockage did quite panic for me. I think the NOT SO HARMLESS robots are programmed with weird too-strict rules. It would be great if you guys can revise the rules, to avoid false positives.

And sorry if I am reporting this issue to wrong repo, I just could not find an appropriate location to raise my concerns. I just want to send you my voice, so that this issue does not happen again.

**Comment by michaeltwofish** [comment]
@hhsadiq This is indeed the wrong repository, this library is not used in GitHub.com and is not responsible for user suspensions.

I'm going to close the issue. [Contacting support](https://github.com/contact) as you've done is the right approach.
